### ISSUE TITLE
exaslct upload command fails

### ISSUE THREAD

**Issue by dixiekong** [exasol/script-languages#109]
I tried uploading the fancy R flavor using the exaslct command as shown in the Readme.
The command fails with the error message:
```python
 File "-/exasol/script-languages-release/script-languages/exaslct_src/lib/docker_build_base.py", line 45, in create_analyze_tasks
    raise Exception(f"Unknown goal(s) {difference}, "
Exception: Unknown goal(s) {('release',)}, following goals are avaialable {'udfclient_deps', 'build_run', 'base_test_build_run', 'flavor_base_deps', 'flavor_test_build_run', 'release', 'base_test_deps', 'flavor_customization', 'build_deps', 'language_deps'}

```
This happens due to a typo in [exaslct_src/cli/commands/upload.py line 84](https://github.com/exasol/script-languages/blob/master/exaslct_src/cli/commands/upload.py#L84):
```python
release_goals=list([release_goal]),

```
The additional brackets put another list around the arguments, which results in the malformed set seen in the stacktrace.

As I understand it the brackets in [exaslct_src/lib/upload_containers_parameter.py](https://github.com/exasol/script-languages/blob/master/exaslct_src/lib/upload_containers_parameter.py) are also redundant too, but I have no clue about luigi.

When removed the command works for me.

**Comment by tkilias** [comment]
Hello @dixiekong,

Thank you for looking into this. Your are right, there is an issue with the upload function. I am already working on a fix. With the next commit to the master, it should be fixed.

**Comment by dixiekong** [comment]
Hello @tkilias,
thanks I have created a PR with the fix I described and a mini typo if of interest. 
I will close this issue.
