### ISSUE TITLE
Unable to find the script_client.proto file needed to build the Python client

### ISSUE THREAD

**Issue by kamon** [exasol/script-languages#17]
I set-up docker running on a ubuntu VM and followed the commands to get the deployment of new script language (https://github.com/EXASOL/script-languages/tree/master/python_client).

When trying to build, I found that the wget call to https://raw.githubusercontent.com/EXASOL/script-languages/master/script_client.proto, included in the script, is not resolving the URL.

Is there a workaround for this procedure to work? Shouldn't the README be updated with the latest details?

Thanks a lot!

**Comment by wildraid** [comment]
@kamon Hello.

I think this file is now available here: https://github.com/EXASOL/script-languages/blob/master/src/zmqcontainer.proto

**Comment by stmandl** [comment]
Thanks, I've updated the path in the Makefile
