### ISSUE TITLE
Performance cpp vs default java implementation

### ISSUE THREAD

**Issue by Sargul** [EXASOL/script-languages#2]
Hi,

just did some testing with the cpp sample container.

Performance ist horrible compared to the included java implementation.

Sample cpp:
````cpp
CREATE OR REPLACE CPP SCALAR SCRIPT LIBRARY."PERF" ("x" VARCHAR(1024) UTF8) RETURNS CHAR(40) UTF8 AS
using namespace UDFClient;

void run_cpp(const Metadata& meta, InputTable& iter, OutputTable& res)
{
	size_t *length;
	const char *data = iter.getString(0, length);
	res.setString(0,data, *length);
        res.next();
        res.flush();
}
````

Same Routine in Java:
````java
CREATE or replace JAVA SCALAR SCRIPT LIBRARY."PERF1" ("TEST" VARCHAR(1024) UTF8) RETURNS CHAR(40) UTF8 AS
%jvmoption -Xms4m;  

class PERF1 { 
	static String run(ExaMetadata exa, ExaIterator ctx) throws Exception 
	{ 
		String out = ctx.getString("TEST");  
		return out ; 
	}
}
````

Performance for 1,000,000 records:
* Java: 1.7 seconds
* c++:  52.8 seconds

That can't be right.

Regards

Charly

**Comment by stmandl** [comment]
Hi Charly!

you are right. I'm going to take a look.

Best,
Stefan

**Comment by stmandl** [comment]
Just a short feedback: I fixed the problem in my local branch. CPP is now faster than Java as we would expect. It's part of a major overhaul of the whole CPP stuff which I will submit after my vacation, so probably sometimes after 25th of August.

**Comment by Sargul** [comment]
Yeaaah

Thank you Stefan

**Comment by Sargul** [comment]
Hi Stefan,

anything new on the CCP overhaul?

Kind Regards

Charly

**Comment by stmandl** [comment]
Hi Charly.
Yes, the commit c7cf29042bebcff21aefbc02c3a8977e69698a41 (just now) should bring major improvements.
Thanks for trying out!
