### ISSUE TITLE
cpp doesn't work anymore

### ISSUE THREAD

**Issue by Sargul** [exasol/script-languages#3]
after the latest commit cpp doesn't work anymore.

VM error: Internal error: VM crashed (Session: 1577860513603653741)

**Comment by stmandl** [comment]
Hi Charly, can you add the UDF here?

**Comment by Sargul** [comment]
same procedure as in #2.  Not even a single row works now.

**Comment by stmandl** [comment]
so, it does not crash anymore?

If so, then remove the flushing of results in every iteration like so:
```

CREATE OR REPLACE CPP SCALAR SCRIPT "PERF" ("x" VARCHAR(1024) UTF8) RETURNS CHAR(40) UTF8 AS

void run_cpp(SWIGMetadata& meta, SWIGTableIterator& iter, SWIGResultHandler& res)
{
	size_t length;
	const char *data = iter.getString(0, & length);
	res.setString(0,data, length);
        res.next();
}
/
```

**Comment by Sargul** [comment]
Does not work even without flush

after 50 seconds I get "VM error: Internal error: VM crashed (Session: 1577860513603653741)".

Event tried the sample csin procedure. Simply does not work anymore

**Comment by stmandl** [comment]
Hmm, that's very bad indeed. What kind of test environment do you use?
I'm using EXASolo with VirtualBox.

**Comment by stmandl** [comment]
I just fixed a bug in README.md which prevented csin() from running.
Did you get this error message with csin():
````
[22002] VM error: Error when trying to load function "run_cpp": 
/tmp/libcode.so: undefined symbol: _Z7run_cppRN16SWIGVMContainers12SWIGMetadataERNS_17SWIGTableIteratorERNS_17SWIGResultHandlerE (Session: 1577838605754711924)
````
If so, good, because the `const` for the argument `meta` was wrong in the example.

**Comment by Sargul** [comment]
Nope I always get "VM error: Internal error: VM crashed (Session: 1577860513603653741)".

Now we tried to completly build the docker container from scratch and use this to create cppclient.tar.gz.

However same result:
"VM error: Internal error: VM crashed (Session: 1577860513603653741)"

We are on 6.0.3 -> just for information.

**Comment by stmandl** [comment]
Really strange. Maybe we are looking at it the wrong way.
Can you send me the SqlSession log files of the query.
Even better: You could try to enable debug output for the UDF like described here: https://github.com/EXASOL/hadoop-etl-udfs#debugging

**Comment by stmandl** [comment]
I just created a new EXASolo in Virtual Box, using 6.0.3.
Everything seems to work fine.
Are you also using Virtual Box or a server installation?

**Comment by Sargul** [comment]
I'm working on a VMWARE ESX Hosted VM. Guest Virtualization Features are enabled. 

I'll try the debug part and provide SqlSession log for this query.

**Comment by stmandl** [comment]
At the moment the CPP implementation it is broken and needs some real love to get going again.
@Sargu, @wildraid, is there currently any real interest in the CPP dialect?
If not, I will close all related issues and move it's now broken implementation to a less prominent place.
Otherwise, are you interested in contributing?

**Comment by wildraid** [comment]
@stmandl , at this moment I am happy with Java. It's easier to maintain, and bottlenecks are either at the external data source or due to parallel reading problem.

**Comment by tkilias** [comment]
Won't fix in the current version
