### ISSUE TITLE
UDF script signature generator is not working

### ISSUE THREAD

**Issue by cyroxx** [exasol/script-languages#34]
The HTMLpreview version of the signature generator does not work in Firefox 64.0.2: [see here](https://htmlpreview.github.io/?https://github.com/EXASOL/script-languages/blob/master/udf-script-signature-generator/udf-script-signature-generator.html)

JS console contains the error `ReferenceError: generate_sql is not defined`

@jschildgen also encountered this issue during a training last week.

**Comment by tkilias** [comment]
Seems to work again with 69.0.1, if you encounter it again, please reopen the ticket, but until then I close it.
