### ISSUE TITLE
make_container.sh fails on MacOS

### ISSUE THREAD

**Issue by wildraid** [exasol/script-languages#5]
MacOS tar fails with error message about unknown arguments --owner and --group in this line:
`tar --numeric-owner --owner=0 --group=0 -zcf ../ScriptLanguages-6.0.2.tar.gz *`

I've removed those arguments, and container seems to be working without any issues. Maybe it's a good idea to fix it in repository.

Thanks.

**Comment by stmandl** [comment]
this issue is out-dated. `make_container.sh` has been removed in favor of `build` and `export` of flavors.
