### ISSUE TITLE
Build TLS certificates for RDS into Java truststore

### ISSUE THREAD

**Issue by redcatbear** [exasol/script-languages#56]
## Situation

A common use case for the script language container is to connect to AWS services. If you want a TLS connection to Amazon's Relational Database Service (RDS), you need to have the RDS certificate bundle installed in your truststore.

By building the bundle into the container we eliminate an inconvenient extra installation step.

## Acceptance Criteria

* Java truststore contains RDS certificate bundle

**Comment by tkilias** [comment]
Now tracked at https://github.com/exasol/script-languages-release/issues/3
